// Generated by CoffeeScript 1.8.0
var scotch;

scotch = ["hello1", "hello2"];

module.exports = function(robot) {
  return robot.hear(/scotch ?me/i, function(msg) {
    return msg.send(msg.random(scotch));
  });
};
