// Generated by CoffeeScript 1.8.0
var scotch;

scotch = ["https://s3.amazonaws.com/scotch-assets/scotch_1.jpg", "https://s3.amazonaws.com/scotch-assets/scotch_2.jpg", "https://s3.amazonaws.com/scotch-assets/scotch_3.jpg", "https://s3.amazonaws.com/scotch-assets/scotch_4.jpg", "https://s3.amazonaws.com/scotch-assets/scotch_5.jpg"];

module.exports = function(robot) {
  return robot.hear(/scotch ?me/i, function(msg) {
    return msg.send(msg.random(scotch));
  });
};
